-   repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v0.9.3
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: requirements-txt-fixer
    -   id: autopep8-wrapper
        exclude: migrations\/[^/]*\.py$|settings\/[^/]*\.py$
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    sha: v1.1.1
    hooks:
    -   id: forbid-crlf
        exclude: \.csv$|\.png$|\.bat$
    -   id: forbid-tabs
        exclude: Makefile|\.bat$
-   repo: https://github.com/prettier/prettier
    sha: 1.6.1
    hooks:
    -   id: prettier
        types: [file]
        files: \.(css|less|scss|html|ts|tsx|graphql|gql|json|js|jsx)$
        exclude: \.min\.(js|css)$
